# Generated by Django 3.1.3 on 2020-12-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acgpr051',
            old_name='d',
            new_name='cfop',
        ),
        migrations.AddField(
            model_name='acgpr051',
            name='cod_mun',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acgpr051',
            name='data',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acgpr051',
            name='inscricao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acgpr051',
            name='numero_nf',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acgpr051',
            name='razao_social',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acgpr051',
            name='valor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
