# Generated by Django 3.1.3 on 2021-02-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appva', '0004_auto_20210201_1814'),
        ('appva', '0004_auto_20210126_1302'),
    ]

    operations = [
    ]
