# Generated by Django 3.1.3 on 2021-02-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appva', '0005_merge_20210203_1440'),
        ('appva', '0005_merge_20210201_1819'),
    ]

    operations = [
    ]
