# Generated by Django 3.1.7 on 2021-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appva', '0007_cci_desc_cnae'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnae',
            name='arbitramento',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
