# Generated by Django 3.1.7 on 2021-03-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appva', '0009_auto_20210309_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=255, null=True)),
                ('inscricao', models.CharField(max_length=255, null=True)),
                ('dtinicio', models.CharField(max_length=255, null=True)),
                ('dtfinal', models.CharField(max_length=255, null=True)),
                ('tipo', models.CharField(max_length=255, null=True)),
                ('dtprocessam', models.CharField(max_length=255, null=True)),
                ('cfop', models.CharField(max_length=255, null=True)),
                ('vlcontabil', models.FloatField(null=True)),
                ('basecalculo', models.FloatField(null=True)),
                ('icms', models.FloatField(null=True)),
                ('isentas', models.FloatField(null=True)),
                ('outras', models.FloatField(null=True)),
                ('ipi', models.FloatField(null=True)),
                ('retido', models.FloatField(null=True)),
                ('situacao', models.CharField(max_length=255, null=True)),
                ('idatualizacao', models.CharField(max_length=255, null=True)),
                ('codmunicipio', models.CharField(max_length=255, null=True)),
                ('efd', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
