# Generated by Django 3.1.7 on 2021-03-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appva', '0010_pts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pts',
            name='ano_base',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pts',
            name='ano_exercicio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pts',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pts',
            name='remessa',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
