# Generated by Django 3.1.7 on 2021-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appva', '0012_auto_20210412_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfop',
            name='tipo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
