# Generated by Django 3.1.7 on 2021-05-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appva', '0013_cfop_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remessas',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
